### ISSUE TITLE
[EPIC 1] Main program

### ISSUE THREAD

**Issue by abumalick** [ahlsunnah/learn-islam-epics#1]
# بسم الله الرحمن الرحيم

## Main program

Madrassah Minhaj app must propose the main program to his users.
- [x] The main program will be in Arabic and French inchaallah
- [x] This main program has 15 mustawa/tracks
- [x] Each mustawa/track have courses of 4 different topics
  - Tawhid
  - Ousoul al Iman
  - Tafsir
  - Others (can be Sira, minhaj, ...)
- [ ] The track's courses will be ordered by topic
- Each Course is divided into Chapters
- Each Chapter has
  - a youtube video
  - an Arabic transcription 
  - maybe some vocabulary
- [x] After each course, a user can take a test with exercises related to the course. The results are not recorded
- [ ] To be able to go to the next mustawa/track, the user must pass the track's exam.
- [ ] We should be able to organize exams for multiple tracks.
- [ ] User registration and login
- [ ] Access to the main program need authentication
